### ISSUE TITLE
Exception in convertGalleriesToImages

### ISSUE THREAD

**Issue by keynmol** [idio/json-wikipedia#12]
When running json-wikipedia on [this xml file](https://gist.github.com/keynmol/c52fc127f28fb2cbaf1c) this exception occurs:

```
java.lang.ArrayIndexOutOfBoundsException: 0
	at de.tudarmstadt.ukp.wikipedia.parser.mediawiki.ModularParser.convertGalleriesToImages(ModularParser.java:1085)
	at de.tudarmstadt.ukp.wikipedia.parser.mediawiki.ModularParser.parse(ModularParser.java:398)
	at it.cnr.isti.hpc.wikipedia.parser.ArticleParser.parse(ArticleParser.java:85)
	at it.cnr.isti.hpc.wikipedia.reader.WikipediaArticleReader$JsonConverter.process(WikipediaArticleReader.java:175)
	at info.bliki.wiki.dump.WikiXMLParser.endElement(WikiXMLParser.java:185)
	at org.apache.xerces.parsers.AbstractSAXParser.endElement(Unknown Source)
	at org.apache.xerces.impl.XMLNSDocumentScannerImpl.scanEndElement(Unknown Source)
	at org.apache.xerces.impl.XMLDocumentFragmentScannerImpl$FragmentContentDispatcher.dispatch(Unknown Source)
	at org.apache.xerces.impl.XMLDocumentFragmentScannerImpl.scanDocument(Unknown Source)
	at org.apache.xerces.parsers.XML11Configuration.parse(Unknown Source)
	at org.apache.xerces.parsers.XML11Configuration.parse(Unknown Source)
	at org.apache.xerces.parsers.XMLParser.parse(Unknown Source)
	at org.apache.xerces.parsers.AbstractSAXParser.parse(Unknown Source)
	at info.bliki.wiki.dump.WikiXMLParser.parse(WikiXMLParser.java:218)
	at it.cnr.isti.hpc.wikipedia.reader.WikipediaArticleReader.start(WikipediaArticleReader.java:136)
	at it.cnr.isti.hpc.wikipedia.cli.MediawikiToJsonCLI.main(MediawikiToJsonCLI.java:137)
```

To reproduce:

```
java -cp target/json-wikipedia-1.1.0-jar-with-dependencies.jar it.cnr.isti.hpc.wikipedia.cli.MediawikiToJsonCLI -input ford_madox_brown.xml -output bla.jsonl -lang en -action export
```

**Comment by keynmol** [comment]
Seems to be because of this line in the article:

```
<gallery mode="packed" heights=" 145px" caption="Ford Madox Brown's works ">|
```

That last `|` is treated like a link to image, and splitting returns empty array.
